# This image requires you to have already built a production version of the UI
# It's only recommended to use this if your destination host is low in compute (e.g. raspberrypi)
FROM alpine:3.9
LABEL maintainer="dj.cass44@gmail.com"

RUN apk add --update nginx

RUN mkdir -p /var/log/nginx
RUN mkdir -p /var/www/html

COPY nginx/nginx.conf /etc/nginx/nginx.conf

WORKDIR /app

COPY ./dist/* /var/www/html/

RUN chown -R nginx:nginx /var/www/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
