kind: pipeline
name: default

steps:
  - name: test
    image: gradle:5.5.1-jdk12
    commands:
      - gradle test
  - name: docker
    image: plugins/docker
    settings:
      repo: djcass44/jmp
      tags:
        - latest
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    event: push