kind: pipeline
name: backend

steps:
  - name: publish
    image: plugins/docker
    settings:
      registry: docker.castive.dev
      repo: docker.castive.dev/jmp
      tags: ${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
  - name: deploy
    image: quay.io/honestbee/drone-kubernetes
    settings:
      deployment: jmp-api
      repo: docker.castive.dev/jmp
      tag: ${DRONE_COMMIT_SHA}
      container: jmp-api
      namespace: default
      kubernetes_server: "https://10.0.1.30:6443"
      kubernetes_cert:
        from_secret: KUBERNETES_CERT
      kubernetes_token:
        from_secret: KUBERNETES_TOKEN