kind: pipeline
name: package

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: docker.castive.dev
      repo: docker.castive.dev/jmp/api
      tags:
        - latest
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
trigger:
  when:
    branch:
      - master
      - develop
    event: push