kind: pipeline
name: backend

platform:
  os: linux
  arch: arm

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: castive-docker-svc-username
      password:
        from_secret: castive-docker-svc-password
      repo: docker.castive.dev/jmp
      registry: docker.castive.dev
    when:
      event:
        - tag
      ref:
        - refs/tags/v*
---
kind: pipeline
name: frontend

platform:
  os: linux
  arch: arm

steps:
  - name: publish-fe
    image: plugins/docker
    settings:
      username:
        from_secret: castive-docker-svc-username
      password:
        from_secret: castive-docker-svc-password
      repo: docker.castive.dev/jmp
      registry: docker.castive.dev
      dockerfile: src/main/resources/public2/Dockerfile
      context: src/main/resources/public2
    when:
      event:
        - tag
      ref:
        - refs/tags/v*