variables:
  AUTO_DEVOPS_CHART: harbor-library/auto-deploy-app
  AUTO_DEVOPS_CHART_REPOSITORY: https://harbor.v2.dcas.dev/chartrepo/library
  AUTO_DEVOPS_CHART_REPOSITORY_NAME: harbor-library
  AUTO_DEVOPS_POSTGRES_CHANNEL: '2'
  CODE_QUALITY_DISABLED: 'true'
  PERFORMANCE_DISABLED: 'true'
  POSTGRES_ENABLED: 'false'
  POSTGRES_VERSION: '12.2'
  HELM_UPGRADE_EXTRA_ARGS: "--atomic"
  KANIKO_CACHE: 'true'
  STAGING_ENABLED: 'true'
  ROLLOUT_RESOURCE_TYPE: 'deployment'

stages:
  - build
  - test
  - deploy  # dummy stage to follow the template guidelines
  - review
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

include:
  - remote: 'https://gitlab.dcas.dev/open-source/gitlab-ci-templates/-/raw/master/auto/Auto-JVM.gitlab-ci.yml'
