variables:
  PERFORMANCE_DISABLED: 'true'
  AUTO_RELEASE_DISABLED: 'false'
  JVM_OPTS: -Xmx1536m
  GRADLE_OPTS: "-Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false"

include:
  - remote: 'https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/auto/Auto-Gradle.gitlab-ci.yml'
