variables:
  PERFORMANCE_DISABLED: 'true'
  TEST_DISABLED: 'true'
  AUTO_RELEASE_DISABLED: 'false'
  AUTO_DEVOPS_REGISTRY: "docker.io/"
  AUTO_DEVOPS_CHART: harbor-library/auto-deploy-app
  AUTO_DEVOPS_CHART_REPOSITORY: https://harbor.v2.dcas.dev/chartrepo/library
  AUTO_DEVOPS_CHART_REPOSITORY_NAME: harbor-library
  AUTO_DEVOPS_POSTGRES_CHANNEL: '2'
  AUTO_DEVOPS_DOCKERFILE: 'https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/auto/jvm/gradle.Dockerfile'
  AUTO_DEVOPS_DOCKERIGNORE: 'https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/auto/jvm/.dockerignore'

stages:
  - prepare
  - verify
  - test
  - build
  - deploy
  - review
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

build gradle:
  stage: build
  extends: .kaniko
  dependencies:
    - prepare_resources
  needs:
    - prepare_resources

include:
  - remote: 'https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/auto/Prepare.gitlab-ci.yml'
  - remote: 'https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/test/Gradle-Test.gitlab-ci.yml'
  - remote: 'https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/verify/bundles/JvmCQ.gitlab-ci.yml'
  - remote: 'https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/build/Kaniko.gitlab-ci.yml'
  - remote: 'https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/deploy/Deploy.gitlab-ci.yml'
  - remote: 'https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/workflows/Push-And-MR.gitlab-ci.yml'
  - remote: "https://gitlab.com/av1o/gitlab-ci-templates/-/raw/master/deploy/AutoRelease.gitlab-ci.yml"
