version: '2'

services:
  jmp:
    image: docker.dev-apps.info/jmp:latest
    ports:
      - "7000:7000"
    volumes:
      - ./data:/data
    environment:
      - DRIVER_URL=jdbc:sqlite:/data/jmp.db
      - DRIVER_CLASS=org.sqlite.JDBC