---
version: '3'
services:
  jmp:
    image: djcass44/jmp
    ports:
      - 7000:7000
  psql:
    image: postgres:12.1-alpine
    ports:
    - 5432:5432
    volumes:
    - db:/var/lib/psql
    environment:
      - POSTGRES_DB=jmp
      - POSTGRES_PASSWORD=password
volumes:
  db:
