---
version: '3'
services:
  psql:
    image: bitnami/postgresql:12.4.0-debian-10-r23
    ports:
    - 5432:5432
    volumes:
    - db:/bitnami/postgresql
    environment:
      - POSTGRES_DATABASE=jmp
      - POSTGRES_PASSWORD=password
volumes:
  db:
