spring:
  application:
    name: jmp
  profiles:
    active: dev
  datasource:
    url: jdbc:sqlite:data/jmp.db
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    config:
      enabled: false
      fail-fast: true
      uri: http://dcas-cloud-config:8888
  jackson:
    default-property-inclusion: non_null

server:
  port: 7000
  servlet:
    context-path: /api

jmp:
  metadata:
    title:
      enabled: true
    icon:
      enabled: false
      url: http://localhost:8080
  security:
    allowCors: true
    baseUrl: http://localhost:7000

security:
  jwt:
    secretKey: "password"
    requestLimit: 3_600_000
    refreshLimit: 86_400_000
    leeway: 3_600_000

logging:
  level:
    dev.castive.jmp: trace
management:
  endpoint:
    health:
      show-details: always
