spring:
  application:
    name: jmp
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/jmp
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
  cloud:
    config:
      enabled: false
      fail-fast: true
      uri: http://dcas-cloud-config:8888
  jackson:
    default-property-inclusion: non_null

server:
  port: 7000
  servlet:
    context-path: /api

jmp:
  metadata:
    title:
      enabled: true
    icon:
      enabled: true
      url: https://icon.dcas.dev
  security:
    allowCors: true
    baseUrl: http://localhost:7000

security:
  jwt:
    secretKey: "password"
    requestLimit: 3_600_000
    refreshLimit: 86_400_000
    leeway: 3_600_000

logging:
  level:
    dev.castive.jmp: trace
management:
  endpoint:
    health:
      show-details: when_authorized
