{{- if .Values.netsec.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            {{- range $key, $val := .Values.netsec.namespace }}
            {{ $key }}: {{ $val }}
            {{- end}}
      - podSelector:
          matchLabels:
            {{- range $key, $val := .Values.netsec.source }}
            {{ $key }}: {{ $val }}
            {{- end}}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    - {}
  policyTypes:
    - Egress
    - Ingress
{{- end }}